# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x64)
  GLFW_config = debug_x64
  GLM_config = debug_x64
  ImGui_config = debug_x64
  hpb_voxel_config = debug_x64

else ifeq ($(config),release_x64)
  GLFW_config = release_x64
  GLM_config = release_x64
  ImGui_config = release_x64
  hpb_voxel_config = release_x64

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := GLFW GLM ImGui hpb-voxel

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C external -f GLFW.make config=$(GLFW_config)
endif

GLM:
ifneq (,$(GLM_config))
	@echo "==== Building GLM ($(GLM_config)) ===="
	@${MAKE} --no-print-directory -C external -f GLM.make config=$(GLM_config)
endif

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C external -f ImGui.make config=$(ImGui_config)
endif

hpb-voxel: GLFW GLM ImGui
ifneq (,$(hpb_voxel_config))
	@echo "==== Building hpb-voxel ($(hpb_voxel_config)) ===="
	@${MAKE} --no-print-directory -C src -f Makefile config=$(hpb_voxel_config)
endif

clean:
	@${MAKE} --no-print-directory -C external -f GLFW.make clean
	@${MAKE} --no-print-directory -C external -f GLM.make clean
	@${MAKE} --no-print-directory -C external -f ImGui.make clean
	@${MAKE} --no-print-directory -C src -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x64"
	@echo "  release_x64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFW"
	@echo "   GLM"
	@echo "   ImGui"
	@echo "   hpb-voxel"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"