# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x64)
  flux_uv_preview_config = debug_x64
  simplevol_config = debug_x64

else ifeq ($(config),release_x64)
  flux_uv_preview_config = release_x64
  simplevol_config = release_x64

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := flux-uv-preview simplevol

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

flux-uv-preview:
ifneq (,$(flux_uv_preview_config))
	@echo "==== Building flux-uv-preview ($(flux_uv_preview_config)) ===="
	@${MAKE} --no-print-directory -C external/flux-uv -f Makefile config=$(flux_uv_preview_config)
endif

simplevol: flux-uv-preview
ifneq (,$(simplevol_config))
	@echo "==== Building simplevol ($(simplevol_config)) ===="
	@${MAKE} --no-print-directory -C src -f Makefile config=$(simplevol_config)
endif

clean:
	@${MAKE} --no-print-directory -C external/flux-uv -f Makefile clean
	@${MAKE} --no-print-directory -C src -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x64"
	@echo "  release_x64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   flux-uv-preview"
	@echo "   simplevol"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"